wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: Graphormer
dataset:
  desc: null
  value: ComplexData
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693303959.027307
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 5
